server:
  port: 8082
spring:
  application:
    name:
      microservice-department

  datasource:
    url: jdbc:h2:mem:departmentDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: optional:configserver:instead
