server:
  port: 8088  # Puerto del Config Server

spring:
  application:
    name: microservice-config  # Nombre del Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cersosimovicente/microservice-config-repo.git  # Repositorio Git
          skipSslValidation: true  # Opción para ignorar validaciones SSL
          clone-on-start: true  # Clonar repo en el arranque del Config Server
          default-label: main  # Rama por defecto (main, master, etc.)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL del Eureka Server
